// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/overview/Content.vue')['default']
    Counter: typeof import('./src/components/counter.vue')['default']
    ErrorInformation: typeof import('./src/components/errorInformation.vue')['default']
    Header: typeof import('./src/components/overview/Header.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    NavigationTiming: typeof import('./src/components/navigationTiming.vue')['default']
    Panel: typeof import('./src/components/shared/Panel.vue')['default']
    PerformanceCard: typeof import('./src/components/performanceCard.vue')['default']
    ResourceFlow: typeof import('./src/components/resourceFlow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UerAction: typeof import('./src/components/uerAction.vue')['default']
  }
}
