// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/counter.vue')['default'];
    ErrorInformation: typeof import('./src/components/errorInformation.vue')['default'];
    Menu: typeof import('./src/components/menu.vue')['default'];
    NavigationTiming: typeof import('./src/components/navigationTiming.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NCollapse: typeof import('naive-ui')['NCollapse'];
    NCollapseItem: typeof import('naive-ui')['NCollapseItem'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NP: typeof import('naive-ui')['NP'];
    NSpace: typeof import('naive-ui')['NSpace'];
    PerformanceCard: typeof import('./src/components/performanceCard.vue')['default'];
    ResourceFlow: typeof import('./src/components/resourceFlow.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    UerAction: typeof import('./src/components/uerAction.vue')['default'];
  }
}
